spring.datasource.jndi-name=java:/jdbc/erpdb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
app.security.jwt.expiration-millis=86400000
app.security.initial-user.username=${ERP_INITIAL_USER:}
app.security.initial-user.password=${ERP_INITIAL_PASSWORD:}
